local M = {}

M.null_ls = {
	-- Taken from: lua/null-ls/methods.lua
	methods = {
		CODE_ACTION = 'NULL_LS_CODE_ACTION',
		DIAGNOSTICS = 'NULL_LS_DIAGNOSTICS',
		DIAGNOSTICS_ON_OPEN = 'NULL_LS_DIAGNOSTICS_ON_OPEN',
		DIAGNOSTICS_ON_SAVE = 'NULL_LS_DIAGNOSTICS_ON_SAVE',
		FORMATTING = 'NULL_LS_FORMATTING',
		RANGE_FORMATTING = 'NULL_LS_RANGE_FORMATTING',
		HOVER = 'NULL_LS_HOVER',
		COMPLETION = 'NULL_LS_COMPLETION',
	},
}

return M
