#!/usr/bin/env sh

IGNORED_DIRS='lazy_spec_wrapper\|custom'

config_dirs=$(find lua -maxdepth 1 -type d | tail -n +2 | grep -v $IGNORED_DIRS | sed -e 's,lua/,,')

for config_dir in $config_dirs; do
    mkdir -p -v ~/.KoalaConfig/$config_dir/
    rm lua/$config_dir/custom
    ln -s -v ~/.KoalaConfig/$config_dir lua/$config_dir/custom
done
